<?php require('template/header.phtml') ?>
<section id="body" class="container">

        <section id="main" class="col-md-8 col-sm-9">
	  
       <h4>Welcome</h4>
       <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis ante felis, a pretium 
    nisl eleifend a. Nam dictum enim eget nisi bibendum 	 molestie. Morbi rhoncus lorem vel mi viverra, non euismod mauris consectetur. Integer mi odio, adipiscing nec metus ut, lobortis feugiat nisi. Aliquam fringilla eu elit eget volutpat. In dolor nulla, vehicula id massa sed, dapibus fringilla neque. Curabitur vel ligula eu ante commodo pulvinar. Sed aliquet purus a elit rutrum bibendum. Praesent nec faucibus nunc. Aliquam aliquam ante purus.
    Pellentesque adipiscing pretium odio, dapibus pretium erat egestas non. Donec interdum lobortis quam, id euismod neque feugiat vitae. 
    Aliquam sed turpis gravida, pharetra velit vel, tempus magna. Donec commodo neque quis elit congue luctus. Praesent interdum molestie dui, et venenatis sem. Cras ligula magna, laoreet sed pulvinar nec, hendrerit at erat. Vestibulum a scelerisque massa, eu egestas mauris. In hac habitasse platea dictumst. Pellentesque id ipsum et lorem interdum faucibus in accumsan ipsum. Integer volutpat, nisl ut lobortis luctus, ipsum dolor accumsan ipsum, vel volutpat risus nibh eu tortor. Ut condimentum condimentum tortor, eu auctor ligula venenatis sed. Nulla tempus sapien at tortor consectetur, non luctus libero sodales. Integer eu leo id felis porttitor mattis ac vitae turpis.</p>
         </section>
	 <section id="sidebar" class="col-md-4 col-sm-3">
	<h2>Tweets</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis ante felis, a pretium nisl eleifend a. Nam dictum enim eget nisi bibendum 	 molestie. Morbi rhoncus lorem vel mi viverra, non euismod mauris consectetur. Integer mi odio, adipiscing nec metus ut, lobortis feugiat nisi. Aliquam fringilla eu elit eget volutpat. In dolor nulla, vehicula id massa sed, dapibus fringilla neque. Curabitur vel ligula eu ante commodo pulvinar. Sed aliquet purus a elit rutrum bibendum. Praesent nec faucibus nunc. Aliquam aliquam ante purus.</p>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis ante felis, a pretium nisl eleifend a. Nam dictum enim eget nisi bibendum 	 molestie. Morbi rhoncus lorem vel mi viverra, non euismod mauris consectetur. Integer mi odio, adipiscing nec metus ut, lobortis feugiat nisi. Aliquam fringilla eu elit eget volutpat. In dolor nulla, vehicula id massa sed, dapibus fringilla neque. Curabitur vel ligula eu ante commodo pulvinar. Sed aliquet purus a elit rutrum bibendum. Praesent nec faucibus nunc. Aliquam aliquam ante purus.</p>
	 </section>
	</section>
        <hr />
<?php require('template/footer.phtml') ?>

