<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset=utf"-8" />
  <meta name="viewport" content= "width=device-width, initial-scale=1.0">
  <title>Homepage - Sentiment Tweets analyse <?php echo $view->pageTitle; ?></title> 
  <link rel="stylesheet" href="css/amelia.css">
  <link rel="stylesheet" href="css/site.css">

<meta http-equiv="content-type" content="text/html;charset=utf-8" />
           
</head>
<body>
  <div id="page">
    <header class="container">
       <div id="menu" class="navbar navbar-default">
	<div class="navbar-header">
	<button class="btn btn-info navbar-toggle"
	data-toggle="collapse"data-target=".navbar-collapse"><span class="glyphicon glyphicon-chevron-down"></span></button>
	             <div id="logo">	
       <h2>Tweets Sentiment Analysis</h2>
       </div>
        </div>
	<div class="navbar-collapse collapse">
         <ul class="nav navbar-nav navbar-right">
		<li><a href="home.php">Home</a></li>
		<li><a href="index.php">Tweets</a></li>
                <li><a href="#">Account</a></li>
        </ul>
      </div>   
    </header>